apiVersion: apps/v1
kind: Deployment
metadata:
  name: alekhya-eta-deploy
  labels:
    app: alekhya-eta-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alekhya-eta-app
  template:
    metadata:
      labels:
        app: alekhya-eta-app
    spec:
      containers:
      - name: alekhya-eta-container
        image: alekhya83/sa-mywebapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: alekhya-eta-np-service
  labels:
    app: alekhya-eta-np-app
spec:
  selector:
    app: alekhya-eta-deploy-lbl

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
